@startuml
actor UserA
participant "FE App A" as FE_A
participant "ws-manager" as WS
participant "write-message-service" as WMS
participant "MongoDB (messages)" as Mongo
participant "Redis (cache)" as Redis
participant "FE App B" as FE_B
actor UserB

UserA -> FE_A: Вводит сообщение
FE_A -> WS: WebSocket: отправка сообщения
WS -> WMS: gRPC/REST: передай сообщение
WMS -> Mongo: Сохранить сообщение
WMS -> Redis: Обновить кеш диалога
WS -> FE_A: Подтверждение отправки

WS -> FE_B: WebSocket Push: Новое сообщение от A
FE_B -> UserB: Отображение уведомления
@enduml
